require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  Include:
    - "**/*.rb"
    - "**/*.rake"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.6
  DisabledByDefault: true
Bundler/DuplicatedGem:
  Enabled: true
Bundler/InsecureProtocolSource:
  Enabled: true
Bundler/OrderedGems:
  Enabled: true
Layout/ConditionPosition:
  Enabled: true
Layout/DefEndAlignment:
  Enabled: true
Layout/ElseAlignment:
  Enabled: true
Layout/EmptyLineAfterMagicComment:
  Enabled: true
Layout/EmptyLineBetweenDefs:
  Enabled: true
Layout/EmptyLines:
  Enabled: true
Layout/IndentationWidth:
  Enabled: true
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: keyword
  AutoCorrect: true
Layout/EndOfLine:
  Enabled: true
Layout/LeadingEmptyLines:
  Enabled: true
Layout/SpaceAroundOperators:
  Enabled: true
Layout/SpaceAroundBlockParameters:
  Enabled: true
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
Layout/IndentationStyle:
  Enabled: true
Layout/TrailingEmptyLines:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true
Lint/AssignmentInCondition:
  Enabled: true
Lint/CircularArgumentReference:
  Enabled: true
Lint/Debugger:
  Enabled: true
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/DuplicateCaseCondition:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/DuplicateHashKey:
  Enabled: true
Lint/EachWithObjectArgument:
  Enabled: true
Lint/EmptyExpression:
  Enabled: true
Lint/EmptyInterpolation:
  Enabled: true
Lint/EmptyWhen:
  Enabled: true
Style/EndBlock:
  Enabled: true
Lint/EnsureReturn:
  Enabled: true
Lint/FloatOutOfRange:
  Enabled: true
Lint/ImplicitStringConcatenation:
  Enabled: true
Lint/IneffectiveAccessModifier:
  Enabled: true
Lint/InterpolationCheck:
  Enabled: true
Lint/LiteralAsCondition:
  Enabled: true
Lint/LiteralInInterpolation:
  Enabled: true
Lint/MultipleComparison:
  Enabled: true
Lint/NestedMethodDefinition:
  Enabled: true
Lint/NestedPercentLiteral:
  Enabled: true
Lint/NextWithoutAccumulator:
  Enabled: true
Lint/NonLocalExitFromIterator:
  Enabled: true
Lint/PercentStringArray:
  Enabled: true
Lint/PercentSymbolArray:
  Enabled: true
Lint/RandOne:
  Enabled: true
Lint/RedundantWithIndex:
  Enabled: true
Lint/RedundantWithObject:
  Enabled: true
Lint/SafeNavigationConsistency:
  Enabled: true
Lint/SafeNavigationWithEmpty:
  Enabled: true
Lint/ShadowedArgument:
  Enabled: true
Lint/ShadowedException:
  Enabled: true
Lint/ShadowingOuterLocalVariable:
  Enabled: true
Lint/RedundantStringCoercion:
  Enabled: true
Lint/Syntax:
  Enabled: true
Lint/ToJSON:
  Enabled: true
Lint/UnderscorePrefixedVariableName:
  Enabled: true
Lint/UnifiedInteger:
  Enabled: true
Lint/RedundantRequireStatement:
  Enabled: true
Lint/RedundantSplatExpansion:
  Enabled: true
Lint/UnreachableCode:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
  AutoCorrect: false
Lint/UselessAccessModifier:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Lint/UselessComparison:
  Enabled: true
Lint/UselessElseWithoutRescue:
  Enabled: true
Lint/UselessSetterCall:
  Enabled: true
Naming/ClassAndModuleCamelCase:
  Enabled: true
Naming/ConstantName:
  Enabled: true
Naming/FileName:
  Enabled: true
Naming/MethodName:
  Enabled: true
Naming/VariableName:
  Enabled: true
Performance/Casecmp:
  Enabled: true
Performance/CompareWithBlock:
  Enabled: true
Performance/Detect:
  Enabled: true
Performance/EndWith:
  Enabled: true
Performance/FlatMap:
  Enabled: true
Performance/InefficientHashSearch:
  Enabled: true
Performance/RangeInclude:
  Enabled: true
Performance/RedundantBlockCall:
  Enabled: true
Performance/RedundantMatch:
  Enabled: true
Performance/RedundantMerge:
  Enabled: true
Style/RedundantSortBy:
  Enabled: true
Performance/RegexpMatch:
  Enabled: true
Performance/ReverseEach:
  Enabled: true
Style/Sample:
  Enabled: true
Performance/Size:
  Enabled: true
Performance/StartWith:
  Enabled: true
Style/RedundantSort:
  Enabled: true
Rails/EnumUniqueness:
  Enabled: true
Rails/EnvironmentComparison:
  Enabled: true
Rails/FindEach:
  Enabled: true
Rails/IgnoredSkipActionFilterOption:
  Enabled: true
Rails/PluralizationGrammar:
  Enabled: true
Rails/RelativeDateConstant:
  Enabled: true
Rails/ReversibleMigration:
  Enabled: true
Rails/SafeNavigation:
  Enabled: true
Security/MarshalLoad:
  Enabled: true
